[env:esp32-s3-deck]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I src/

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    links2004/WebSockets @ ^2.4.1
    lvgl/lvgl @ 9.1.0
    bodmer/TFT_eSPI @ ^2.5.43
